### ISSUE TITLE
add switch channel no cd function

### ISSUE THREAD

**Issue by for40255** [skript023/Tower-of-Fantasy#2]
hi can add switch channel no cd function?

thank you!

**Comment by skript023** [comment]
sry, Im no longer revese this game

**Comment by for40255** [comment]
> sry, Im no longer revese this game

May I ask where can you find QRSLPlayerController??

i want to add a ServerRequestTransferLevel function 

thank you!

i try Uworld->[188]OwningGameInstance->[38]local_player[0]-> [30]PlayerController->[268]Controller
but no work
