### ISSUE TITLE
gamee vresion 2.0 

### ISSUE THREAD

**Issue by for40255** [skript023/Tower-of-Fantasy#5]
no imgui ui view

**Comment by skript023** [comment]
what did you mean no imgui view? if imgui not showing probably there are issues in hook I can't help too much, since Im no longer have the game

**Comment by for40255** [comment]
game version 2.0 no longer runs dxd11 so maybe is problem 
I am trying to join the dxd12 renderer

the is log 

`LogZeusBuild: Cleaning working directory: C:/Users/s10022306/AppData/Local/Temp/ZeusBuildPluginDir/
LogDLSSNGXVulkanRHIPreInit: FNGXVulkanRHIPreInitModule::StartupModule Enter
LogD3D12RHI: Aftermath initialized
LogDXGIBridge: calling DXGIBridge::CreateDXGIFactory through FDXGIDefaultFunctions
LogDXGIBridge: DXGIBridge::FDXGIDefaultFunctions::CreateDXGIFactory
LogD3D12Bridge: calling D3D12Bridge::D3D12CreateDevice via FD3D12DefaultFunctions
LogD3D12Bridge: D3D12Bridge::FD3D12DefaultFunctions::D3D12CreateDevice
LogD3D12RHI: Found D3D12 adapter 0: NVIDIA GeForce GTX 1060 (Max supported Feature Level 12_1)
LogD3D12RHI: Adapter has 6052MB of dedicated video memory, 0MB of dedicated system memory, and 8117MB of shared system memory, 1 output[s]
LogD3D12Bridge: calling D3D12Bridge::D3D12CreateDevice via FD3D12DefaultFunctions
LogD3D12Bridge: D3D12Bridge::FD3D12DefaultFunctions::D3D12CreateDevice
LogD3D12RHI: Found D3D12 adapter 1: Intel(R) UHD Graphics 630 (Max supported Feature Level 12_1)
LogD3D12RHI: Adapter has 128MB of dedicated video memory, 0MB of dedicated system memory, and 8117MB of shared system memory, 0 output[s]
LogD3D12Bridge: calling D3D12Bridge::D3D12CreateDevice via FD3D12DefaultFunctions
LogD3D12Bridge: D3D12Bridge::FD3D12DefaultFunctions::D3D12CreateDevice
LogD3D12RHI: Found D3D12 adapter 2: Microsoft Basic Render Driver (Max supported Feature Level 12_1)
LogD3D12RHI: Adapter has 0MB of dedicated video memory, 0MB of dedicated system memory, and 8117MB of shared system memory, 0 output[s]
LogD3D12RHI: Chosen D3D12 Adapter Id = 0
LogDLSSNGXVulkanRHIPreInit: GetSelectedDynamicRHIModuleName = D3D12RHI
LogDLSSNGXVulkanRHIPreInit: VulkanRHI is not the active DynamicRHI; skipping of pregistering the required NGX DLSS Vulkan device and instance extensions via the VulkanRHIBridge
LogDLSSNGXVulkanRHIPreInit: FNGXVulkanRHIPreInitModule::StartupModule Leave
LogInit: Using libcurl 7.55.1-DEV`

**Comment by for40255** [comment]
hi i have some question

class ULevel : public UObject
{
  public:
  char pad_0000[0x98];
  TArray<AActor*> m_actor; //0x98
};

m_actor <<--- how can find m_actor offset in dump.host i want to update esp , esp in 2.0 not  work 

thank ans

**Comment by skript023** [comment]
Idk how to find it in dump.host, but you can look at cheat engine or ReClass in UWorld->ULevel

**Comment by for40255** [comment]
> Idk how to find it in dump.host, but you can look at cheat engine or ReClass in UWorld->ULevel

sorry i don't understand what you mean i mean +98 how this offset is obtained uworld->[140]levels->[98]m_actor

https://i.imgur.com/RJMWJPt.png

**Comment by for40255** [comment]
i dont knwo how to find m_actor(offset)

**Comment by for40255** [comment]
fixed thank
